service: sample-demo-bot

provider:
  name: aws
  runtime: python3.6
  timeout: 20
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    LUIS_APP_ID: ${env:LUIS_APP_ID}
    LUIS_APP_KEY: ${env:LUIS_APP_KEY}
    READMINE_KEY_ID: ${env:READMINE_KEY_ID}
    READMINE_IP: ${env:READMINE_IP}


custom:
  pythonRequirements:
    dockerizePip: false

functions:
  sample_telegram:
    handler: telegram_bot.publish_telegram_msg
    events:
      - http:
          path: teleg-bot-demo
          method: post
          cors: true
    #alarms: # merged with function alarms
    #  - customAlarm
    #  - name: teleg-bot-demo-Alarm # creates new alarm or overwrites some properties of the alarm (with the same name) from definitions
    #    namespace: 'AWS/Lambda'
    #    metric: errors # define custom metrics here
    #    threshold: 1
    #    statistic: Minimum
    #    period: 60
    #    evaluationPeriods: 1
    #    comparisonOperator: GreaterThanOrEqualToThreshold


plugins:
  - serverless-plugin-aws-alerts
  - serverless-python-requirements
